### ISSUE TITLE
Was it intentional to move this repo into CoderAcademy-ALL?

### ISSUE THREAD

**Issue by AlexStormwood** [yops320/Liam_Kung_T3A2_RosterTrack_Server#1]
We can't install any extra integrations like the Cloudflare Pages that was requested, and we're not sure why this repo was moved into this organisation... if you need help moving this repo out of this organisation, let us know. 

The repo will be easier to manage if you have full control over it, and you might not have that level of control over this repo when it's part of this organisation.

**Comment by yops320** [comment]
Sonny asked me to move it to CA all
I'll clarify with him why.

Could you move it back then sorry Alex?

**Comment by AlexStormwood** [comment]
![image](https://github.com/CoderAcademy-ALL/Liam_Kung_T3A2_RosterTrack_Server/assets/22165407/9090906e-ec15-4474-b284-3bbc055c01c1)


It looks like Sonny has to do this, otherwise this repo may be locked into here.

**Comment by yops320** [comment]
I've sent him a message on discord.

I'm a bit confused now.
@double0kung

**Comment by AlexStormwood** [comment]
Ah, I've figured out a way -- 

I can transfer the repo from the CA-ALL org to myself, then from myself to either of you. But the transfer to either of you is a _request_, it has to be approved on your end. 

So, Sonny has a request waiting for approval to get the repo back into his account.

**Comment by yops320** [comment]
Nice one, thanks alex.
You can do it to me if you want, no issue at all. I'm currently online & he's likely busy.

**Comment by AlexStormwood** [comment]
Good idea, request will come through shortly.

Want me to do this for the frontend repo too?

**Comment by yops320** [comment]
Might as well.

Thanks Alex

**Comment by double0kung** [comment]
Apologies my bad, I misunderstood the lesson about joining an organisation
to make it easier to connect to the repo via 3rd party services.

Cheers
Sonny

**Comment by AlexStormwood** [comment]
I see - you two can absolutely make an organisation together, then you'd both have control over the repos. But transferring a repo to some other organisation where you don't have admin rights means that you limit your control over your own work.

Make sure you have admin rights over your repo! ;)
